hash-format = "sha256"

[[files]]
file = "config/ballotbox.toml"

[[files]]
file = "config/bobby.conf"

[[files]]
file = "config/chunksfadein.properties"

[[files]]
file = "config/crunchy_crunchy_advancements.toml"

[[files]]
file = "config/emi.css"

[[files]]
file = "config/fireblanket/fireblanket.txt"

[[files]]
file = "config/hoofprint.toml"

[[files]]
file = "config/modernfix-mixins.properties"

[[files]]
file = "config/quickerconnectbutton.json5"

[[files]]
file = "config/roles.json"

[[files]]
file = "config/simplefog.json"

[[files]]
file = "config/styled-chat.json"

[[files]]
file = "config/styled-nicknames.json"

[[files]]
file = "config/styled_chat_emoji.json"

[[files]]
file = "config/styledplayerlist/config.json"

[[files]]
file = "config/styledplayerlist/styles/default.json"

[[files]]
file = "config/surveyor.toml"

[[files]]
file = "config/teabridge.json"

[[files]]
file = "config/waila/waila.json"

[[files]]
file = "config/waila/waila_plugins.json"

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/area-tools.pw.toml"
metafile = true

[[files]]
file = "mods/area_lib.pw.toml"
metafile = true

[[files]]
file = "mods/armorstandeditor.pw.toml"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
metafile = true

[[files]]
file = "mods/ballotbox.pw.toml"
metafile = true

[[files]]
file = "mods/barricade.pw.toml"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/crunchy-crunchy-advancements.pw.toml"
metafile = true

[[files]]
file = "mods/drogstyle.pw.toml"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fabrictailor.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/fireblanket-0.6.2+1.21.jar"

[[files]]
file = "mods/glide-away.pw.toml"
metafile = true

[[files]]
file = "mods/glowcase.pw.toml"
metafile = true

[[files]]
file = "mods/hoofprint.pw.toml"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
metafile = true

[[files]]
file = "mods/map-utils.pw.toml"
metafile = true

[[files]]
file = "mods/meret-6.0.0.jar"

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/now-playing-fabric-1.5.13+stereomerge+1.21.jar"

[[files]]
file = "mods/placeholder-api.pw.toml"
metafile = true

[[files]]
file = "mods/player-pronouns.pw.toml"
metafile = true

[[files]]
file = "mods/player-roles.pw.toml"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
metafile = true

[[files]]
file = "mods/qdwarp.pw.toml"
metafile = true

[[files]]
file = "mods/quicker-connect-button.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/scattered-shards.pw.toml"
metafile = true

[[files]]
file = "mods/simple-resource-loader.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/simplefog.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/spawnanywhere.pw.toml"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
metafile = true

[[files]]
file = "mods/styled-nicknames.pw.toml"
metafile = true

[[files]]
file = "mods/styledplayerlist.pw.toml"
metafile = true

[[files]]
file = "mods/surveyor.pw.toml"
metafile = true

[[files]]
file = "mods/switchy-proxy.pw.toml"
metafile = true

[[files]]
file = "mods/switchy.pw.toml"
metafile = true

[[files]]
file = "mods/teabridge.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
metafile = true

[[files]]
file = "options.txt"

[[files]]
file = "resources/common/required/mf_music/assets/minecraft/models/item/music_disc_cat.json"

[[files]]
file = "resources/common/required/mf_music/assets/minecraft/sounds.json"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/lang/en_us.json"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/models/item/music/dormant.json"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/models/item/music/mechanical_plateau.json"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/sounds.json"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/sounds/music/dormant.ogg"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/sounds/music/mechanical_plateau.ogg"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/sounds/music/stereo/dormant.ogg"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/sounds/music/stereo/mechanical_plateau.ogg"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/textures/item/music/dormant.png"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/textures/item/music/mechanical_plateau.png"

[[files]]
file = "resources/common/required/mf_music/assets/now-playing/sprites.json"

[[files]]
file = "resources/common/required/mf_music/data/modfest/jukebox_song/dormant.json"

[[files]]
file = "resources/common/required/mf_music/data/modfest/jukebox_song/mechanical_plateau.json"

[[files]]
file = "resources/common/required/mf_music/data/modfest/jukebox_song/stereo/dormant.json"

[[files]]
file = "resources/common/required/mf_music/data/modfest/jukebox_song/stereo/mechanical_plateau.json"

[[files]]
file = "resources/common/required/mf_music/data/modfest/tags/jukebox_song/area_override_volcano_trail.json"

[[files]]
file = "resources/common/required/mf_music/pack.mcmeta"

[[files]]
file = "resources/common/required/mf_music/pack.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/lang/en_us.json"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/coconut_backing.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/coconut_front.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/coconut_mini_backing.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/coconut_mini_front.png"

[[files]]
file = "resources/common/required/mf_shards/data/scattered_shards/shard_type/types.json"

[[files]]
file = "resources/common/required/mf_shards/pack.mcmeta"

[[files]]
file = "resources/datapack/required/mf_ballotbox/data/ballotbox/ballot/categories.json"

[[files]]
file = "resources/datapack/required/mf_ballotbox/data/ballotbox/ballot/options.json"

[[files]]
file = "resources/datapack/required/mf_ballotbox/pack.mcmeta"

[[files]]
file = "resources/datapack/required/mf_fireblanket/data/fireblanket/tags/block/block_interaction_restricted.json"

[[files]]
file = "resources/datapack/required/mf_fireblanket/data/fireblanket/tags/entity_type/entity_attack_restricted.json"

[[files]]
file = "resources/datapack/required/mf_fireblanket/data/fireblanket/tags/entity_type/entity_interaction_restricted.json"

[[files]]
file = "resources/datapack/required/mf_fireblanket/data/fireblanket/tags/item/item_interaction_restricted.json"

[[files]]
file = "resources/datapack/required/mf_fireblanket/pack.mcmeta"

[[files]]
file = "resources/resourcepack/required/Unsanded-1.1.1-custom.zip"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/texts/credits.json"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/gui/title/background/panorama_0.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/gui/title/background/panorama_1.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/gui/title/background/panorama_2.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/gui/title/background/panorama_3.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/gui/title/background/panorama_4.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/gui/title/background/panorama_5.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/gui/title/edition.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/gui/title/minecraft.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/gui/title/mojangstudios.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/misc/forcefield.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/modfest/textures/art/graphics/background-lockup.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/modfest/textures/art/graphics/lockup-transparent.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/modfest/textures/art/icon/transparent-modfest.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/pack.mcmeta"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/font/emoji.json"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/font/icons.json"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/ace_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/agender_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/aro_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/aroace_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/bi_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/blanketcon.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/blob_waaaaa.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/demi_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/femboy_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/furry_pride.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/genderfluid_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/genderflux_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/genderqueer_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/intersex_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/lesbian_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/lil_pineapple.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/modfest-generic.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/nb_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/neurodiversity_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/ohno.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/pan_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/pineapple.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/plural_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/queer_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/queer_prog_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/trans_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/uh.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/vincian_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/whyfest.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/winnger.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/yeefuckinghaw.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/pack.mcmeta"

[[files]]
file = "resources/resourcepack/required/mf_emoji/styled_chat_emoji.json"

[[files]]
file = "resources/resourcepack/required/twemoji.zip"

[[files]]
file = "server-icon.png"

[[files]]
file = "server.properties"

[[files]]
file = "servers.dat"
