name = "BlanketCon '25"
author = "ModFest"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
unsup = "1.0-rc2"

[options]
no-internal-hashes = true
